repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: Check - YAML
      - id: end-of-file-fixer
        name: Check - End Files on New Line
      - id: trailing-whitespace
        name: Remove Trailing Whitespace
        stages: [commit, push, manual]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
        name: Check - Poetry Configuration
        stages: [commit, push, manual]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.259"
    hooks:
      - id: ruff
        name: Linting - ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Formatting - black
        stages: [commit, push, manual]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Formatting - isort
        stages: [commit, push, manual]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        name: Static Type Checking - mypy
        stages: [commit, push, manual]
        args: ["--config-file", "pyproject.toml"]
        files: '.*\.py[i]?'
