name: maldi-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipywidgets
  - tqdm
  - numpy
  - pandas
  - xarray
  - scipy
  - scikit-image
  - matplotlib
  - pip:
    - alpineer
    - .
